spring:
  config:
    import: optional:secrets.yaml

detector:
  s3:
    endpoint: "http://s3:9000"
    bucket-name: "development"

client:
  frontier:
    url: "http://frontier:3000"

logging:
  config: classpath:logback.xml
